title: Digital Mindfulness
tagline: Bewussterer Umgang mit E-Mail und Co

author:
  name: Florian Mann
  url: https://twitter.com/florianmann

permalink: /:title

sass:
  style: :compressed

google_analytics_id: UA-77441823-1

exclude:
  - README.md
